apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit
  namespace: monitoring
  labels:
    k8s-app: fluentbit
    addonmanager.kubernetes.io/mode: Reconcile
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentbit
  labels:
    k8s-app: fluentbit
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentbit
  namespace: monitoring
  labels:
    k8s-app: fluentbit
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: fluentbit
  namespace: monitoring
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentbit
  apiGroup: ""

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: log-config
  namespace: monitoring
data:
  Region: "Dev"
  Zone: "Dev"
  webvLog: "webvdev"
  ngsaLog: "ngsadev"

---
apiVersion: v1
kind: Secret
metadata:
  name: log-secrets
  namespace: monitoring
type: Opaque
data:
  WorkspaceId: ZGV2Cg==
  SharedKey: ZGV2Cg==

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output.conf

  output.conf: |
    [OUTPUT]
        Name                grafana-loki
        Match               kube.var.log.containers.ngsa*.*
        Url                 https://$GC_LOKI_USER:$GC_PAT@logs-prod-us-central1.grafana.net/loki/api/v1/push
        Labels              {job="ngsa"}
        LabelKeys           k_app,k_namespace,Date,Category,StatusCode,Duration,Path,Region,Zone,Mode
        RemoveKeys          Date,Category,StatusCode,Duration,Path,Region,Zone,Mode,k_app,kubernetes_namespace_name

  input-kubernetes.conf: |
    [INPUT]
        Name                tail
        Tag                 kube.*
        Path                /var/log/containers/*.log
        Parser              cri
        DB                  /var/log/flb_kube.db
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     Off
        Refresh_Interval    10

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Trim      On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         Off
        Labels              On

    [FILTER]
        Name                nest
        Match               kube.*
        Operation           lift
        Nested_under        kubernetes
        Add_prefix          kubernetes_

    [FILTER]
        Name                nest
        Match               kube.*
        Operation           lift
        Nested_under        kubernetes_labels
        Add_prefix          kubernetes_labels_

    [FILTER]
        Name    modify
        Match   kube.*
        Copy    kubernetes_labels_app.kubernetes.io/instance   k_app
        Copy    kubernetes_labels_app                          k_app
        Copy    kubernetes_container_name                      k_container

  parsers.conf: |
    [PARSER]
        Name         json
        Format       json
        Time_Key     time
        Time_Format  %d/%b/%Y:%H:%M:%S %z
        Time_Keep    Off

    [PARSER]
        Name         syslog
        Format       regex
        Regex        ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key     time
        Time_Format  %b %d %H:%M:%S

    [PARSER]
        Name         cri
        Format       regex
        Regex        ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L
        Time_Keep    Off

---

apiVersion: v1
kind: Pod
metadata:
  name: fluentbit
  namespace: monitoring
  labels:
    app: fluentbit
spec:
    priorityClassName: system-node-critical
    serviceAccountName: fluentbit
    terminationGracePeriodSeconds: 10

    securityContext:
      seccompProfile:
        type: RuntimeDefault

    containers:
    - name: fluent-bit
      image: grafana/fluent-bit-plugin-loki:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 2020
      resources:
        limits:
          cpu: 200m
          memory: 256Mi

      env:
      # - name: WorkspaceId
      #   valueFrom:
      #     secretKeyRef:
      #       name: log-secrets
      #       key: WorkspaceId

      # - name: SharedKey
      #   valueFrom:
      #     secretKeyRef:
      #       name: log-secrets
      #       key: SharedKey

      # - name: ngsaLog
      #   valueFrom:
      #     configMapKeyRef:
      #       name: log-config
      #       key: ngsaLog

      # - name: webvLog
      #   valueFrom:
      #     configMapKeyRef:
      #       name: log-config
      #       key: webvLog

      - name: Zone
        valueFrom:
          configMapKeyRef:
            name: log-config
            key: Zone

      - name: Region
        valueFrom:
          configMapKeyRef:
            name: log-config
            key: Region

      volumeMounts:
      - name: varlog
        mountPath: /var/log

      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true

      - name: fluent-bit-config
        mountPath: /fluent-bit/etc/

    volumes:
    - name: varlog
      hostPath:
        path: /var/log

    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers

    - name: fluent-bit-config
      configMap:
        name: fluent-bit-config
